### ISSUE TITLE
FC037 -- Crashes on notifies with resources() calls

### ISSUE THREAD

**Issue by docwhat** [Foodcritic/foodcritic#201]
This code crashes foodcritic 2.2.0 on rule FC037:

```
template '/etc/monit/monitrc' do
  owner 'root'
  group 'root'
  mode 0700
  source 'monitrc.erb'
  notifies :restart, resources(service: 'monit'), :delayed
end
```

From http://leopard.in.ua/2013/12/01/chef-and-tdd/ -- specifically the initial commit of [recipes/default.rb](https://github.com/le0pard/chef-tdd-monit/blob/cf590fc93f2d1477dd91ea9d6bfba73edb52b919/recipes/default.rb)

Error:

```
∓ foodcritic -t FC037 .
/usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/chef.rb:67:in `resource_check?': Arguments cannot be nil or empty. (ArgumentError)
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/chef.rb:18:in `resource_action?'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/rules.rb:493:in `block (5 levels) in load'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/rules.rb:488:in `each'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/rules.rb:488:in `any?'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/rules.rb:488:in `block (4 levels) in load'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.11/lib/nokogiri/xml/node_set.rb:237:in `block in each'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.11/lib/nokogiri/xml/node_set.rb:236:in `upto'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/nokogiri-1.5.11/lib/nokogiri/xml/node_set.rb:236:in `each'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/rules.rb:487:in `select'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/rules.rb:487:in `block (3 levels) in load'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/linter.rb:199:in `yield'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/linter.rb:199:in `matches'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/linter.rb:63:in `block (2 levels) in check'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/linter.rb:62:in `each'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/linter.rb:62:in `block in check'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/linter.rb:59:in `each'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/linter.rb:59:in `check'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/lib/foodcritic/linter.rb:28:in `check'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/bin/foodcritic:5:in `<module:FoodCritic>'
        from /usr/local/var/rbenv/versions/2.0.0-p353/lib/ruby/gems/2.0.0/gems/foodcritic-2.2.0/bin/foodcritic:3:in `<top (required)>'
        from /Users/docwhat/Vagrants/sushi/.bundle/bin/foodcritic:16:in `load'
        from /Users/docwhat/Vagrants/sushi/.bundle/bin/foodcritic:16:in `<main>'
```

It looks similar to issue #104

**Comment by shortdudey123** [comment]
I am seeing this on foodcritic 4.0.0 and only with FC037 w. Ruby 2.1.5
```
hostname:~/path username $ bundle exec foodcritic -t FC037 .
/Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/chef.rb:69:in `resource_check?': Arguments cannot be nil or empty. (ArgumentError)
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/chef.rb:16:in `resource_action?'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:559:in `block (5 levels) in load'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:554:in `each'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:554:in `any?'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:554:in `block (4 levels) in load'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:187:in `block in each'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `upto'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/nokogiri-1.6.6.2/lib/nokogiri/xml/node_set.rb:186:in `each'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:553:in `select'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/rules.rb:553:in `block (3 levels) in load'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:241:in `yield'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:241:in `matches'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:97:in `cookbook_matches'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:75:in `block (2 levels) in check'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:64:in `each'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:64:in `block in check'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:56:in `each'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:56:in `check'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/lib/foodcritic/linter.rb:26:in `check'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/bin/foodcritic:5:in `<module:FoodCritic>'
    from /Users/username/path/.bundle/ruby/2.1.0/gems/foodcritic-4.0.0/bin/foodcritic:3:in `<top (required)>'
    from /Users/username/path/.bundle/ruby/2.1.0/bin/foodcritic:23:in `load'
    from /Users/username/path/.bundle/ruby/2.1.0/bin/foodcritic:23:in `<main>'
hostname:~/path username $
```

**Comment by shortdudey123** [comment]
It works if i change the call to `bundle exec foodcritic -t FC037 ./` (ending `/`)

**Comment by jaredbonobos** [comment]
any update on this? having the same issue now on 4.0.0 with ruby 2.15

**Comment by c240amg** [comment]
Happens to me on foodcritic 6.0.0 on ruby 2.0.1 (chefdk)
Obviously workaround is to put ~FC037 in the .foodcritic file.

**Comment by AntonOfTheWoods** [comment]
And also 6.3.0 on ruby 2.1.8 (chefdk)

**Comment by joegoggins** [comment]
Still a problem here on these versions

```
$ chef exec foodcritic --version
foodcritic 7.1.0
```

```
$ chef --version
Chef Development Kit Version: 0.18.26
chef-client version: 12.14.89
delivery version: master (d86679335580be3de22996ef294b20d525889d8d)
berks version: 5.1.0
kitchen version: 1.13.0
```

**Comment by tas50** [comment]
This works with my latest PR to fix FC037 notification parsing: https://github.com/Foodcritic/foodcritic/pull/736
